"""0003_add_a_field_to_identify_popular_issuers

Revision ID: 1fe85ac37845
Revises: a822e95849ad
Create Date: 2026-03-24 15:54:16.014202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1fe85ac37845'
down_revision: Union[str, Sequence[str], None] = 'a822e95849ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('is_popular', sa.Boolean(), nullable=False,server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor', 'is_popular')
    # ### end Alembic commands ###
