"""0006_exam_request

Revision ID: 71096806ce42
Revises: 8037dfd65b4d
Create Date: 2026-03-26 12:25:28.714043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '71096806ce42'
down_revision: Union[str, Sequence[str], None] = '8037dfd65b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('exam_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('vendor_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('exam_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_review', 'completed', name='examrequeststatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_request_email'), 'exam_request', ['email'], unique=False)
    op.create_index(op.f('ix_exam_request_exam_name'), 'exam_request', ['exam_name'], unique=False)
    op.create_index(op.f('ix_exam_request_status'), 'exam_request', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_request_status'), table_name='exam_request')
    op.drop_index(op.f('ix_exam_request_exam_name'), table_name='exam_request')
    op.drop_index(op.f('ix_exam_request_email'), table_name='exam_request')
    op.drop_table('exam_request')
    # ### end Alembic commands ###
