"""0007_generation_job

Revision ID: 757a4a0a852d
Revises: 71096806ce42
Create Date: 2026-03-26 14:56:13.656958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '757a4a0a852d'
down_revision: Union[str, Sequence[str], None] = '71096806ce42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('exam_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='jobstatus'), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completed_steps', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('result_exam_id', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['result_exam_id'], ['exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_job_status'), 'generation_job', ['status'], unique=False)
    op.drop_column('exam_request', 'vendor_name')
    op.drop_column('exam_request', 'exam_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_request', sa.Column('exam_code', sa.VARCHAR(length=50), nullable=True))
    op.add_column('exam_request', sa.Column('vendor_name', sa.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_generation_job_status'), table_name='generation_job')
    op.drop_table('generation_job')
    # ### end Alembic commands ###
