"""0005_ad_text

Revision ID: 8037dfd65b4d
Revises: 8e1d07c972a7
Create Date: 2026-03-24 19:22:06.250714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '8037dfd65b4d'
down_revision: Union[str, Sequence[str], None] = '8e1d07c972a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement', sa.Column('ad_text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisement', 'ad_text')
    # ### end Alembic commands ###
