"""0004_advertisement

Revision ID: 8e1d07c972a7
Revises: 1fe85ac37845
Create Date: 2026-03-24 19:00:24.845922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '8e1d07c972a7'
down_revision: Union[str, Sequence[str], None] = '1fe85ac37845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('notify_on_click', sa.Boolean(), nullable=False),
    sa.Column('is_generic_ad', sa.Boolean(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Enum('banner', 'sidebar', 'inline', name='adposition'), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('starts_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ends_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertisement_exam_id'), 'advertisement', ['exam_id'], unique=False)
    op.create_index(op.f('ix_advertisement_title'), 'advertisement', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advertisement_title'), table_name='advertisement')
    op.drop_index(op.f('ix_advertisement_exam_id'), table_name='advertisement')
    op.drop_table('advertisement')
    # ### end Alembic commands ###
