"""0002_metadata_and_additional_fields

Revision ID: a822e95849ad
Revises: 3c5fa2408a99
Create Date: 2026-03-24 10:50:30.160920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a822e95849ad'
down_revision: Union[str, Sequence[str], None] = '3c5fa2408a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('managed_order_id', sa.Integer(), nullable=False))
    op.add_column('question', sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('question', sa.Column('extra_metadata', sa.JSON(), nullable=True))
    op.drop_column('test', 'instructions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('instructions', sa.VARCHAR(), nullable=True))
    op.drop_column('question', 'extra_metadata')
    op.drop_column('question', 'llm_model')
    op.drop_column('exam', 'managed_order_id')
    # ### end Alembic commands ###
